### ISSUE TITLE
GIF : The media could not be played

### ISSUE THREAD

**Issue by Lynzl** [sferik/x-ruby#22]
Hello,

When I send a GIF to X, there's an error on the X's side saying that the media could not be played.

I followed the example [post_media_upload.rb](https://github.com/sferik/x-ruby/blob/main/examples/post_media_upload.rb) replacing `tweet_image` by `tweet_gif`.

I tried to use different GIF and tested it with multiple devices.

Thanks in advance and have a nice day.

**Comment by sferik** [comment]
Can you please attach the GIFs you are attempting to upload here?

**Comment by Lynzl** [comment]
Sure.
![gif1](https://github.com/sferik/x-ruby/assets/61295948/f3e007e1-c80d-4baa-955b-d6a22aedb156)
![gif2](https://github.com/sferik/x-ruby/assets/61295948/c3ad9f82-68b1-425a-b17e-85c5aa923b48)

**Comment by sferik** [comment]
As you probably noticed, I've been doing a bit of testing and debugging. No solutions yet, but I wanted to post an update with the results:
* I [posted](https://twitter.com/gem/status/1752417838244221211) the first cat GIF via the API (both chunked and unchunked). In both cases, the upload succeeded and the correct GIF thumbnail appeared in the post, but when I attempted to play the GIF, it resulted in the error "The media could not be played" (on web) or "Content is not available" (on mobile).
* I [posted](https://twitter.com/gem/status/1752762489434177690) the same cat GIF via the website and it worked perfectly, indicating that the problem was not a corrupted GIF.
* I [posted](https://twitter.com/gem/status/1752477712705601676) a different GIF via the API and it worked perfectly, indicating that *some* GIFs can be uploaded via this library without issue.

I’ll do some more testing and debugging today. I just wanted to provide a quick update of what I’ve found so far.

**Comment by Lynzl** [comment]
Thank you very much for your investigation!

**Comment by sferik** [comment]
Update: Today I tried base64-encoding the image data, since I thought sending binary data over the wire might be causing an issue (this could explain why some GIF uploads were working while others were not). This did not fix the issue.

I’ve also generated a minimal (97 byte) animated GIF, that is 10×10 pixels and flashes back and forth between red (`#ff0000`) and blue (`#0000ff`) every half second. This GIF reproduces the issue but spews less binary (or base-64 encoded) data in the debug output than the cat images you provided.

![animated](https://github.com/sferik/x-ruby/assets/10308/e4e4ee89-db33-4622-b70e-bbd323c6b12e)

**Comment by sferik** [comment]
Mystery solved (I think). From the [upload media API documentation](https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/api-reference/post-media-upload):

> * Please note that to upload videos or GIFs (`tweet_video`, `amplify_video`, and `tweet_gif`), you need to use the [chunked upload end-point](https://developer.twitter.com/en/docs/media/upload-media/api-reference/post-media-upload-init).

To implement this, simply make the following change to your code:

```diff
-media = X::MediaUploader.upload(client: client, file_path: file_path, media_category: media_category)
+media = X::MediaUploader.chunked_upload(client: client, file_path: file_path, media_category: media_category)
+
+X::MediaUploader.await_processing(client: client, media: media)
```

I have tested this by posted [these](https://twitter.com/gem/status/1753191867825758533) [images](https://twitter.com/gem/status/1753208868094795875) via the API, both of which look good to me.

In addition to using the chunked API, you must also adhere to the following constraints on animated GIFs (from [uploading media best practices](https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/uploading-media/media-best-practices)):

* Resolution should be ≤ 1280×1080 (width × height)
* Number of frames ≤ 350
* Number of pixels (width × height × num_frames) ≤ 300 million
* File size ≤ 15MB

By default, the `MediaUploader.chunked_upload` method splits files into 8MB chunks, but you can override that with the `chunk_size_mb` parameter, which takes a `Numeric` (`Integer` or `Float`) as its argument.

Please confirm that this solves the problem for you after you have a chance to test it yourself.

**Comment by Lynzl** [comment]
It works! Thank you very much for your investment investigating the issue.
