### ISSUE TITLE
POST media/upload Support

### ISSUE THREAD

**Issue by imack** [sferik/x-ruby#4]
Looking through the codebase, don't see any references to [media/upload](https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/api-reference/post-media-upload) on the 1.1 api or info in the docs. 

Is this on the roadmap and/or are you open to PRs that port the functionality from the old twitter gem?

**Comment by sferik** [comment]
@imack Thanks for opening this issue! It’s possible to use the API v1.1 `media/upload` endpoint with the `x` gem, though I will admit it’s a bit cumbersome. Here is some example code:

```ruby
require "x"

x_credentials = {
  api_key:             "INSERT YOUR X API KEY HERE",
  api_key_secret:      "INSERT YOUR X API KEY SECRET HERE",
  access_token:        "INSERT YOUR X ACCESS TOKEN HERE",
  access_token_secret: "INSERT YOUR X ACCESS TOKEN SECRET HERE",
}

boundary = "AaB03x"

upload_client = X::Client.new(base_url: "https://upload.twitter.com/1.1/", content_type: "multipart/form-data, boundary=#{boundary}", **x_credentials)

file_path = "path/to/your/image.jpg"

post_body = []
post_body << "--#{boundary}\r\n"
post_body << "Content-Disposition: form-data; name=\"media\"; filename=\"#{File.basename(file_path)}\"\r\n"
post_body << "Content-Type: image/jpeg\r\n"
# Or use the mime-types gem to dynamically determine the content type
# require "mime/types"
# post_body << "Content-Type: #{MIME::Types.type_for(file_path).first.content_type}\r\n"
post_body << "\r\n"
post_body << File.read(file_path)
post_body << "\r\n--#{boundary}--\r\n"

upload_client.post("media/upload.json?media_category=tweet_image", post_body.join)
```

An example using the chunked media endpoint is even more cumbersome, but should still be possible with the existing `x` gem.

I suppose the relevant questions are:
* Should we attempt to make this any easier?
* If so, then how?

One solution would simply be to provide sample code, similar to the above, either to the `README` or elsewhere in the repository (e.g. an `examples` directory). The main benefit of this approach is that it keeps the gem simple and lean, without adding external dependencies (like the `mime-types` gem) for those who don’t need it.

On the other hand, it’s not particularly user-friendly to require anyone who wants to post media to manually construct a multi-part request. I’m open to a pull request that would make this easier. Ideally, it would be done in a way that isn’t tightly-coupled to the existing `media/upload` endpoint, since API v1.1 is being phased out. If you have ideas for interface changes, I’m interested to hear them. I’d suggest we discuss them here before you get started on an implementation.

**Comment by imack** [comment]
Interesting. `mime-types` doesn't seem like a particularly onerous dependency, but I can see your desire to keep it lean. 

Maybe just keep it in the readme for now for people who are otherwise looking for a client function? 

This code chunk you so generously provided solved our problem and maybe waiting until a v2 replacement comes out it's fine to just have it as a documented option.

**Comment by sferik** [comment]
@imack I’ve added a new `X::MediaUpload` helper and updated the [examples](https://github.com/sferik/x-ruby/blob/main/examples/post_media_upload.rb) to show how to use it. This should allow you to greatly simplify your code. This will be included in the next release of this gem (version 0.10.0).

**Comment by pranaybinju** [comment]
> @imack I’ve added a new `X::MediaUpload` helper and updated the [examples](https://github.com/sferik/x-ruby/blob/main/examples/post_media_upload.rb) to show how to use it. This should allow you to greatly simplify your code. This will be included in the next release of this gem (version 0.10.0).

@sferik 
I tried uploading image from a remote URL, but I get an error 
> File not found: https://s3.amazonaws.com/law-media-dev/uploads/1/20/small/oc-gonzalez-xg8z_KhSorQ-unsplash-4.jpg?1717665536

Is there any way, we can upload image file from remote URL ? or is it needed to be on local machine as per the [code](https://github.com/sferik/x-ruby/blob/main/examples/post_media_upload.rb#L12) ?
